namespace UI {
  enum OperatingSystem {
    ANDROID
    IOS
    LINUX
    OSX
    UNKNOWN
    WINDOWS
  }

  enum UserAgent {
    CHROME
    EDGE
    FIREFOX
    IE
    SAFARI
    UNKNOWN
  }

  interface Platform {
    def operatingSystem OperatingSystem
    def userAgent UserAgent
    def nowInSeconds double
    def createWindow Window # This may return null when called multiple times

    def baseModifier Modifiers {
      return operatingSystem == .OSX ? .META : .CONTROL
    }
  }
}
