const GLSLX_SOURCE_SOLID_BATCH_VERTEX = "precision highp float;uniform vec2 c;attribute vec4 d,f;varying vec2 a;varying vec4 b;void main(){a=d.zw,b=f,gl_Position=vec4(d.xy*c-sign(c),0,1);}"
const GLSLX_SOURCE_SOLID_BATCH_FRAGMENT = "precision highp float;varying vec2 a;varying vec4 b;void main(){gl_FragColor=b*min(1.,min(a.x,a.y));}"
const GLSLX_SOURCE_GLYPH_BATCH_VERTEX = "precision highp float;uniform vec2 c;attribute vec4 d,f;varying vec2 a;varying vec4 b;void main(){a=d.zw,b=f,gl_Position=vec4(d.xy*c-sign(c),0,1);}"
const GLSLX_SOURCE_GLYPH_BATCH_FRAGMENT = "precision highp float;uniform sampler2D h;varying vec2 a;varying vec4 b;void main(){gl_FragColor=b*texture2D(h,a).r;}"

const GLSLX_NAME_SCALE2 = "c"
const GLSLX_NAME_POSITION4 = "d"
const GLSLX_NAME_COLOR4 = "f"
const GLSLX_NAME_TEXTURE = "h"
